services:
  postgres:
    env_file:
      - .env
    build:
      context: ../../../../
      dockerfile: /deploy/docker/env/dev/db.Dockerfile
    ports:
      - '5432:5432'

  keycloak:
    build:
      context: ../../../../
      dockerfile: /deploy/docker/env/dev/keycloak.Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  medical-care-service:
    env_file: .env
    build:
      context: ../../../../
      dockerfile: /deploy/docker/env/dev/service.Dockerfile
      args:
        - JAR_VERSION=${JAR_VERSION}
    environment:
      api.version: $API_VERSION
      profile: $PROFILE
      shell.on: $SHELL_ON
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    volumes:
      - ../../../../:/app