server:
  servlet:
    context-path: /api/${api.version}

spring:
  profiles:
    active: ${profile}

---
spring:
  application:
    name: medical-care-service
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/medical_care_db
    username: postgres
    password: root
  config:
    activate:
      on-profile: dev