server:
  port: 8081

spring:
  profiles:
    active: ${profile}
  application:
    name: medical-care-service
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
  shell:
    interactive:
      enabled: true
  webflux:
    base-path: /api/${api.version}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/realms/medical-care
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/medical-care

app:
  shell: ${shell.on}

---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/medical_care_service_db
    username: postgres
    password: root

  config:
    activate:
      on-profile: dev

---
spring:
  r2dbc:
    url: r2dbc:h2:mem:///medical_care_service_db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect