name: Default CI/CD

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - '!master'

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  test:
    uses: ./.github/workflows/test.yaml
    needs: build