name: Default CI/CD

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - '!master'

jobs:

  build:
    uses: job/build.yaml
    with:
      java-version: 17

  test:
    uses: job/test.yaml
    needs: build
    with:
      java-version: 17