name: Main CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    uses: ./.github/workflows/job/build.yaml
    with:
      java-version: 17

  test:
    uses: ./.github/workflows/job/test.yaml
    needs: build
    with:
      java-version: 17